/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MiniTwitter;

import java.awt.Color;
import java.util.Enumeration;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

public class AdminControlPanelUI extends javax.swing.JFrame {

    private Group root = new Group("root");
    
    private int usrSize = 0;
    
    private int grpSize = 0;
    
    private int msgSize = 0;
    
    private DefaultTreeModel treeModel = new DefaultTreeModel(root);
    
    /**
     * Creates new form AdminControlPanelUI
     */
    public AdminControlPanelUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        dialog.setLocationRelativeTo(null);
        TreeSelectionModel model = treeList.getSelectionModel();
        model.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        dialogText = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeList = new javax.swing.JTree();
        userIDText = new javax.swing.JTextField();
        groupIDText = new javax.swing.JTextField();
        addUserButton = new javax.swing.JButton();
        addGroupButton = new javax.swing.JButton();
        userViewButton = new javax.swing.JButton();
        usrTotalButton = new javax.swing.JButton();
        grpTotalButton = new javax.swing.JButton();
        msgTotalButton = new javax.swing.JButton();
        posPctButton = new javax.swing.JButton();

        dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialog.setMinimumSize(new java.awt.Dimension(100, 80));
        dialog.setPreferredSize(new java.awt.Dimension(200, 100));
        dialog.setResizable(false);
        dialog.setSize(new java.awt.Dimension(200, 100));

        dialogText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        dialogText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dialogText.setText("Text");
        dialogText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dialogText)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dialogText)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Control Panel");
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));

        mainPanel.setForeground(new java.awt.Color(204, 204, 204));
        mainPanel.setLocation(new java.awt.Point(0, 0));

        treeList.setModel(treeModel);
        treeList.setAutoscrolls(true);
        treeList.setScrollsOnExpand(true);
        treeList.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeList);

        userIDText.setForeground(new java.awt.Color(102, 102, 102));
        userIDText.setText("Enter User ID");
        userIDText.setPreferredSize(new java.awt.Dimension(80, 25));
        userIDText.setSize(new java.awt.Dimension(80, 25));
        userIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userIDTextFocusLost(evt);
            }
        });

        groupIDText.setForeground(new java.awt.Color(102, 102, 102));
        groupIDText.setText("Enter Group ID");
        groupIDText.setPreferredSize(new java.awt.Dimension(80, 25));
        groupIDText.setSize(new java.awt.Dimension(80, 25));
        groupIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                groupIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                groupIDTextFocusLost(evt);
            }
        });

        addUserButton.setText("Add User");
        addUserButton.setToolTipText("Click to add user id to the list");
        addUserButton.setPreferredSize(new java.awt.Dimension(95, 29));
        addUserButton.setSize(new java.awt.Dimension(95, 29));
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        addGroupButton.setText("Add Group");
        addGroupButton.setPreferredSize(new java.awt.Dimension(95, 29));
        addGroupButton.setSize(new java.awt.Dimension(95, 29));
        addGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupButtonActionPerformed(evt);
            }
        });

        userViewButton.setText("Open User View");
        userViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userViewButtonActionPerformed(evt);
            }
        });

        usrTotalButton.setText("Show User Total");
        usrTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTotalButtonActionPerformed(evt);
            }
        });

        grpTotalButton.setText("Show Group Total");
        grpTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpTotalButtonActionPerformed(evt);
            }
        });

        msgTotalButton.setText("Show Message Total");
        msgTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTotalButtonActionPerformed(evt);
            }
        });

        posPctButton.setText("Show Pos Pencentage");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(groupIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(userViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(grpTotalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(msgTotalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(posPctButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usrTotalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(groupIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(userViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(usrTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grpTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(msgTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(posPctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void usrTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTotalButtonActionPerformed
        dialogText.setText("Total Users: " + usrSize);
        dialog.setVisible(true);
    }//GEN-LAST:event_usrTotalButtonActionPerformed

    private void grpTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpTotalButtonActionPerformed
        dialogText.setText("Total Groups: " + grpSize);
        dialog.setVisible(true);
    }//GEN-LAST:event_grpTotalButtonActionPerformed

    private void msgTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTotalButtonActionPerformed
        dialogText.setText("Total Messages: " + msgSize);
        dialog.setVisible(true);
    }//GEN-LAST:event_msgTotalButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        String text = userIDText.getText();
        if(text.equals("Enter User ID") || text.equals("")) { 
        } else {
            boolean alreadyIn = false;
            DefaultMutableTreeNode temp = null;
            for(Enumeration e = root.depthFirstEnumeration(); e.hasMoreElements() && temp == null;) {
                DefaultMutableTreeNode uNode = (DefaultMutableTreeNode) e.nextElement();
                if(uNode.toString().equals(text)) {
                    alreadyIn = true;
                    temp = uNode;
                }
            }
            
            if (alreadyIn == false) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeList.getLastSelectedPathComponent();
        
                if(node == null) {
                    node = (DefaultMutableTreeNode) treeList.getModel().getRoot();
                }
                
                if(!node.getAllowsChildren()) {
                    node = (DefaultMutableTreeNode) node.getParent();
                }
                
                User childNode = new User(text);
                
                treeModel.insertNodeInto(childNode, node, node.getChildCount());
                
                treeList.scrollPathToVisible(new TreePath(childNode.getPath()));
                
                usrSize++;
                
                userIDText.setForeground(new Color(102, 102, 102));
                userIDText.setText("Enter User ID");
            }
        }
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupButtonActionPerformed
        String text = groupIDText.getText();
        if(text.equals("Enter Group ID") || text.equals("")) {
        } else {
            boolean alreadyIn = false;
            DefaultMutableTreeNode temp = null;
            for(Enumeration e = root.breadthFirstEnumeration(); e.hasMoreElements() && temp == null;) {
                DefaultMutableTreeNode gNode = (DefaultMutableTreeNode) e.nextElement();
                if(gNode.toString().equals(text)) {
                    alreadyIn = true;
                    temp = gNode;
                }
            }
            
            if(alreadyIn == false){
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeList.getLastSelectedPathComponent();
        
                if(node == null) {
                    node = (DefaultMutableTreeNode) treeList.getModel().getRoot();
                } 
                
                if(!node.getAllowsChildren()) {
                    node = (DefaultMutableTreeNode) node.getParent();
                }

                Group childNode = new Group(text);

                treeModel.insertNodeInto(childNode, node, node.getChildCount());

                treeList.scrollPathToVisible(new TreePath(childNode.getPath()));

                grpSize++;
                
                groupIDText.setForeground(new Color(102, 102, 102));
                groupIDText.setText("Enter Group ID");
            }
        }
    }//GEN-LAST:event_addGroupButtonActionPerformed

    private void userViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userViewButtonActionPerformed
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) treeList.getLastSelectedPathComponent();
        UserViewUI ui;
        if(n == null || n.getAllowsChildren()) {
            dialogText.setText("Not an user ID!");
            dialog.setVisible(true);
        } else {
            User node = (User) treeList.getLastSelectedPathComponent();
            ui = new UserViewUI(root, node);
            ui.setVisible(true);
//            while(ui.isShowing()) {
//                this.msgSize = this.msgSize + ui.msgSize;
//                System.out.println(msgSize);
//            }
            
        }
    }//GEN-LAST:event_userViewButtonActionPerformed

    private void treeListValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeListValueChanged
        
    }//GEN-LAST:event_treeListValueChanged

    private void userIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userIDTextFocusGained
        if(userIDText.getText().equals("Enter User ID")) {
            userIDText.setText("");
            userIDText.setForeground(Color.black);
        }
    }//GEN-LAST:event_userIDTextFocusGained

    private void userIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userIDTextFocusLost
        if(userIDText.getText().equals("")) {
            userIDText.setForeground(new Color(102, 102, 102));
            userIDText.setText("Enter User ID");
        }
    }//GEN-LAST:event_userIDTextFocusLost

    private void groupIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_groupIDTextFocusGained
        if(groupIDText.getText().equals("Enter Group ID")) {
            groupIDText.setText("");
            groupIDText.setForeground(Color.black);
        }
    }//GEN-LAST:event_groupIDTextFocusGained

    private void groupIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_groupIDTextFocusLost
        if(groupIDText.getText().equals("")) {
            groupIDText.setForeground(new Color(102, 102, 102));
            groupIDText.setText("Enter Group ID");
        }
    }//GEN-LAST:event_groupIDTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanelUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanelUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JDialog dialog;
    private javax.swing.JLabel dialogText;
    private javax.swing.JTextField groupIDText;
    private javax.swing.JButton grpTotalButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton msgTotalButton;
    private javax.swing.JButton posPctButton;
    private javax.swing.JTree treeList;
    private javax.swing.JTextField userIDText;
    private javax.swing.JButton userViewButton;
    private javax.swing.JButton usrTotalButton;
    // End of variables declaration//GEN-END:variables
}
