/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MiniTwitter;

import java.awt.Color;
import java.util.Calendar;
import java.util.Enumeration;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

public class AdminControlPanelUI extends javax.swing.JFrame {

    private UserNode root = new UserNode("root", true);
    
    private UserNode userForDialog;
    
    private int usrSize = 0;
    
    private int grpSize = 0;
    
    private int msgSize = 0;
    
    private int pp = 0;
    
    private Calendar c;
    
    private String lastID = "N/A";
    
    private String lastTime = "N/A";
    
    private boolean valid = true;
    
    DefaultListModel fList = new DefaultListModel();
    
    DefaultListModel mList = new DefaultListModel();
    
    private final DefaultTreeModel treeModel = new DefaultTreeModel(root);
    
    /**
     * Creates new form AdminControlPanelUI
     */
    public AdminControlPanelUI() {
        fList.addElement("Following: ");
        mList.addElement("Messages: ");
        initComponents();
        this.setLocationRelativeTo(null);
        dialog.setLocationRelativeTo(null);
        userViewDialog.setLocationRelativeTo(null);
        TreeSelectionModel model = treeList.getSelectionModel();
        model.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog = new javax.swing.JDialog();
        dialogText = new javax.swing.JLabel();
        userViewDialog = new javax.swing.JDialog();
        usrIDText = new javax.swing.JTextArea();
        followButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FollowingList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgText = new javax.swing.JTextArea();
        tweetButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        msgList = new javax.swing.JList();
        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeList = new javax.swing.JTree();
        userIDText = new javax.swing.JTextField();
        groupIDText = new javax.swing.JTextField();
        addUserButton = new javax.swing.JButton();
        addGroupButton = new javax.swing.JButton();
        userViewButton = new javax.swing.JButton();
        usrTotalButton = new javax.swing.JButton();
        grpTotalButton = new javax.swing.JButton();
        msgTotalButton = new javax.swing.JButton();
        posPctButton = new javax.swing.JButton();
        verifButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();

        dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialog.setMinimumSize(new java.awt.Dimension(100, 80));
        dialog.setResizable(false);
        dialog.setSize(new java.awt.Dimension(200, 100));

        dialogText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        dialogText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dialogText.setText("Text");
        dialogText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dialogLayout = new javax.swing.GroupLayout(dialog.getContentPane());
        dialog.getContentPane().setLayout(dialogLayout);
        dialogLayout.setHorizontalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dialogText)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogLayout.setVerticalGroup(
            dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(dialogText)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        userViewDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        userViewDialog.setMinimumSize(new java.awt.Dimension(400, 480));
        userViewDialog.setName("userViewDialog"); // NOI18N
        userViewDialog.setSize(new java.awt.Dimension(400, 490));

        usrIDText.setColumns(20);
        usrIDText.setForeground(new java.awt.Color(102, 102, 102));
        usrIDText.setRows(1);
        usrIDText.setText("Enter User ID");
        usrIDText.setAutoscrolls(false);
        usrIDText.setPreferredSize(new java.awt.Dimension(255, 35));
        usrIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usrIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usrIDTextFocusLost(evt);
            }
        });

        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        FollowingList.setModel(fList);
        FollowingList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        FollowingList.setMinimumSize(new java.awt.Dimension(40, 85));
        FollowingList.setSelectionModel(new NoSelectionModel());
        FollowingList.setVisibleRowCount(5);
        jScrollPane2.setViewportView(FollowingList);

        msgText.setColumns(20);
        msgText.setForeground(new java.awt.Color(102, 102, 102));
        msgText.setRows(4);
        msgText.setText("Tweet Message");
        msgText.setPreferredSize(new java.awt.Dimension(165, 75));
        msgText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msgTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                msgTextFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(msgText);

        tweetButton.setText("Tweet");
        tweetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetButtonActionPerformed(evt);
            }
        });

        msgList.setModel(mList);
        msgList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        msgList.setMinimumSize(new java.awt.Dimension(40, 85));
        msgList.setSelectionModel(new NoSelectionModel());
        msgList.setVisibleRowCount(5);
        jScrollPane4.setViewportView(msgList);

        javax.swing.GroupLayout userViewDialogLayout = new javax.swing.GroupLayout(userViewDialog.getContentPane());
        userViewDialog.getContentPane().setLayout(userViewDialogLayout);
        userViewDialogLayout.setHorizontalGroup(
            userViewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userViewDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userViewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userViewDialogLayout.createSequentialGroup()
                        .addComponent(usrIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(followButton))
                    .addGroup(userViewDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tweetButton))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        userViewDialogLayout.setVerticalGroup(
            userViewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userViewDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(userViewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(followButton)
                    .addComponent(usrIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(userViewDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tweetButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Control Panel");
        setName("mainFrame"); // NOI18N
        setSize(new java.awt.Dimension(640, 480));

        mainPanel.setForeground(new java.awt.Color(204, 204, 204));

        treeList.setModel(treeModel);
        treeList.setAutoscrolls(true);
        jScrollPane1.setViewportView(treeList);

        userIDText.setForeground(new java.awt.Color(102, 102, 102));
        userIDText.setText("Enter User ID");
        userIDText.setPreferredSize(new java.awt.Dimension(80, 25));
        userIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userIDTextFocusLost(evt);
            }
        });

        groupIDText.setForeground(new java.awt.Color(102, 102, 102));
        groupIDText.setText("Enter Group ID");
        groupIDText.setPreferredSize(new java.awt.Dimension(80, 25));
        groupIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                groupIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                groupIDTextFocusLost(evt);
            }
        });

        addUserButton.setText("Add User");
        addUserButton.setToolTipText("Click to add user id to the list");
        addUserButton.setPreferredSize(new java.awt.Dimension(95, 29));
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        addGroupButton.setText("Add Group");
        addGroupButton.setPreferredSize(new java.awt.Dimension(95, 29));
        addGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupButtonActionPerformed(evt);
            }
        });

        userViewButton.setText("Open User View");
        userViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userViewButtonActionPerformed(evt);
            }
        });

        usrTotalButton.setText("Show User Total");
        usrTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrTotalButtonActionPerformed(evt);
            }
        });

        grpTotalButton.setText("Show Group Total");
        grpTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpTotalButtonActionPerformed(evt);
            }
        });

        msgTotalButton.setText("Show Message Total");
        msgTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTotalButtonActionPerformed(evt);
            }
        });

        posPctButton.setText("Show Pos Pencentage");
        posPctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posPctButtonActionPerformed(evt);
            }
        });

        verifButton.setText("Verify IDs");
        verifButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifButtonActionPerformed(evt);
            }
        });

        lastButton.setText("Last Updated");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(groupIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(grpTotalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(msgTotalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(posPctButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usrTotalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(verifButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(groupIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(addGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(userViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(verifButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(lastButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(usrTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grpTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(msgTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(posPctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void usrTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrTotalButtonActionPerformed
        dialogText.setText("Total Users: " + usrSize);
        dialog.setVisible(true);
    }//GEN-LAST:event_usrTotalButtonActionPerformed

    private void grpTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpTotalButtonActionPerformed
        dialogText.setText("Total Groups: " + grpSize);
        dialog.setVisible(true);
    }//GEN-LAST:event_grpTotalButtonActionPerformed

    private void msgTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTotalButtonActionPerformed
        dialogText.setText("Total Messages: " + msgSize);
        dialog.setVisible(true);
    }//GEN-LAST:event_msgTotalButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        String text = userIDText.getText();
        
        if(text.equals("Enter User ID") || text.equals("")) { 
        } else {
            boolean alreadyIn = false;
            DefaultMutableTreeNode temp = null;
            for(Enumeration e = root.depthFirstEnumeration(); e.hasMoreElements() && temp == null;) {
                DefaultMutableTreeNode uNode = (DefaultMutableTreeNode) e.nextElement();
                if(uNode.toString().equals(text)) {
                    alreadyIn = true;
                    temp = uNode;
                }
            }
            
            if (!alreadyIn) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeList.getLastSelectedPathComponent();
        
                if(node == null) {
                    node = (DefaultMutableTreeNode) treeList.getModel().getRoot();
                }
                
                if(!node.getAllowsChildren()) {
                    node = (DefaultMutableTreeNode) node.getParent();
                }
                
                String[] s = text.split("\\s+");
                
                valid = (s.length <= 1);
                
                UserNode childNode = new UserNode(text);
                
                treeModel.insertNodeInto(childNode, node, node.getChildCount());
                
                treeList.scrollPathToVisible(new TreePath(childNode.getPath()));
                
                usrSize++;
                
                userIDText.setForeground(new Color(102, 102, 102));
                userIDText.setText("Enter User ID");
            }
        }
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupButtonActionPerformed
        String text = groupIDText.getText();
        if(text.equals("Enter Group ID") || text.equals("")) {
        } else {
            boolean alreadyIn = false;
            DefaultMutableTreeNode temp = null;
            for(Enumeration e = root.breadthFirstEnumeration(); e.hasMoreElements() && temp == null;) {
                DefaultMutableTreeNode gNode = (DefaultMutableTreeNode) e.nextElement();
                if(gNode.toString().equals(text)) {
                    alreadyIn = true;
                    temp = gNode;
                }
            }
            
            if(alreadyIn == false){
                DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeList.getLastSelectedPathComponent();
        
                if(node == null) {
                    node = (DefaultMutableTreeNode) treeList.getModel().getRoot();
                } 
                
                if(!node.getAllowsChildren()) {
                    node = (DefaultMutableTreeNode) node.getParent();
                }

                UserNode childNode = new UserNode(("(G)" + text), true);

                treeModel.insertNodeInto(childNode, node, node.getChildCount());

                treeList.scrollPathToVisible(new TreePath(childNode.getPath()));

                grpSize++;
                
                groupIDText.setForeground(new Color(102, 102, 102));
                groupIDText.setText("Enter Group ID");
            }
        }
    }//GEN-LAST:event_addGroupButtonActionPerformed

    private void userViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userViewButtonActionPerformed
        DefaultMutableTreeNode n = (DefaultMutableTreeNode) treeList.getLastSelectedPathComponent();
        if(n == null || n.getAllowsChildren()) {
            dialogText.setText("Not an user ID!");
            dialog.setVisible(true);
        } else {
            this.userForDialog = (UserNode) treeList.getLastSelectedPathComponent();
            this.fList.clear();
            this.fList.addElement("following:");
            for(int i = 0; i < this.userForDialog.getFollowings().size(); i++) {
                this.fList.addElement("  " + this.userForDialog.getFollowings().get(i));
            }
            this.mList.clear();
            this.mList.addElement("Messages: ");
            for(int i = 0; i < this.userForDialog.getMessage().size(); i++) {
                this.mList.addElement("  " + this.userForDialog.getMessage().get(i));
            }
            userViewDialog.setTitle(this.userForDialog.getID());
            usrIDText.setText("Enter User ID");
            msgText.setText("Tweet Message");
            userViewDialog.setVisible(true);
            System.out.println(userForDialog.getID() + " created at " 
                    + userForDialog.getCreateTime());
        }
    }//GEN-LAST:event_userViewButtonActionPerformed

    private void userIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userIDTextFocusGained
        if(userIDText.getText().equals("Enter User ID")) {
            userIDText.setText("");
            userIDText.setForeground(Color.black);
        }
    }//GEN-LAST:event_userIDTextFocusGained

    private void userIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userIDTextFocusLost
        if(userIDText.getText().equals("")) {
            userIDText.setForeground(new Color(102, 102, 102));
            userIDText.setText("Enter User ID");
        }
    }//GEN-LAST:event_userIDTextFocusLost

    private void groupIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_groupIDTextFocusGained
        if(groupIDText.getText().equals("Enter Group ID")) {
            groupIDText.setText("");
            groupIDText.setForeground(Color.black);
        }
    }//GEN-LAST:event_groupIDTextFocusGained

    private void groupIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_groupIDTextFocusLost
        if(groupIDText.getText().equals("")) {
            groupIDText.setForeground(new Color(102, 102, 102));
            groupIDText.setText("Enter Group ID");
        }
    }//GEN-LAST:event_groupIDTextFocusLost

    private void usrIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrIDTextFocusGained
        if(usrIDText.getText().equals("Enter User ID")) {
            usrIDText.setText("");
            usrIDText.setForeground(Color.black);
        }
    }//GEN-LAST:event_usrIDTextFocusGained

    private void usrIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrIDTextFocusLost
       if(usrIDText.getText().equals("")) {
            usrIDText.setForeground(new Color(102, 102, 102));
            usrIDText.setText("Enter User ID");
        }
    }//GEN-LAST:event_usrIDTextFocusLost

    private void msgTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgTextFocusGained
        if(msgText.getText().equals("Tweet Message")) {
            msgText.setText("");
            msgText.setForeground(Color.black);
        }
    }//GEN-LAST:event_msgTextFocusGained

    private void msgTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgTextFocusLost
        if(msgText.getText().equals("")) {
            msgText.setForeground(new Color(102, 102, 102));
            msgText.setText("Tweet Message");
        }
    }//GEN-LAST:event_msgTextFocusLost

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
        String text = usrIDText.getText();
        
        if(!userForDialog.getID().equals(text)) {
            boolean alreadyIn = false;

            for(int i = 0; i < userForDialog.getFollowings().size(); i++) {
                if(userForDialog.getFollowings().get(i).equals(text)){
                    alreadyIn = true;
                    i = userForDialog.getFollowings().size();
                }
            }
            
            if(!alreadyIn) {
                DefaultMutableTreeNode ftemp = null;
                for(Enumeration e = root.depthFirstEnumeration(); e.hasMoreElements() && ftemp == null;) {
                    UserNode uNode = (UserNode) e.nextElement();
                    if(uNode.toString().equals(text) && (!uNode.getAllowsChildren())) {
                        userForDialog.getFollowings().add(text);
                        fList.addElement("  " + uNode.getID());
                        uNode.getFollowings().add(userForDialog.getID());
                        ftemp = uNode;
                    }
                }
            }
        }
    }//GEN-LAST:event_followButtonActionPerformed

    private void tweetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetButtonActionPerformed
        String text = msgText.getText();
        this.mList.addElement("  " + userForDialog.getID() + ": " + text);
        userForDialog.getMessage().add("  " + userForDialog.getID() + ": " + text);
        c = Calendar.getInstance();
        userForDialog.setLastUpdate(c);
        lastID = userForDialog.getID();
        lastTime = userForDialog.getLastUpdate();
        System.out.println("Last Updated: " + lastID + " " + lastTime);
        
        DefaultMutableTreeNode ftemp = null;
        for(Enumeration e = root.depthFirstEnumeration(); e.hasMoreElements() && ftemp == null;) {
            UserNode uNode = (UserNode) e.nextElement();
            for(int i = 0; i < userForDialog.getFollowers().size(); i++) {
                if((!uNode.getAllowsChildren()) && uNode.toString().equals(userForDialog.getFollowers().get(i))) {
                    uNode.getMessage().add("  " + userForDialog.getID() + ": " + text);
                    uNode.setLastUpdate(c);
                }
            }
        }
        String[] text2 = text.split("\\s");
        for(int i = 0; i < text2.length; i++) {
            if(text2[i].equals("nice") || text2[i].equals("good") || text2[i].equals("wonderful")) {
                pp++;
                i = text2.length;
            }
        }
        msgSize++;
        pp = pp/msgSize;
    }//GEN-LAST:event_tweetButtonActionPerformed

    private void posPctButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posPctButtonActionPerformed
        dialogText.setText("Pos Percentage: " + pp + "%");
        dialog.setVisible(true);
    }//GEN-LAST:event_posPctButtonActionPerformed

    private void verifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifButtonActionPerformed
        if(valid) {
            System.out.println("All IDs are valid.");
        } else {
            System.out.println("Not all IDs are valid.");
        }
    }//GEN-LAST:event_verifButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        System.out.println("Last Updated: " + lastID + " " + lastTime);
    }//GEN-LAST:event_lastButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList FollowingList;
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JDialog dialog;
    private javax.swing.JLabel dialogText;
    private javax.swing.JButton followButton;
    private javax.swing.JTextField groupIDText;
    private javax.swing.JButton grpTotalButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton lastButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JList msgList;
    private javax.swing.JTextArea msgText;
    private javax.swing.JButton msgTotalButton;
    private javax.swing.JButton posPctButton;
    private javax.swing.JTree treeList;
    private javax.swing.JButton tweetButton;
    private javax.swing.JTextField userIDText;
    private javax.swing.JButton userViewButton;
    private javax.swing.JDialog userViewDialog;
    private javax.swing.JTextArea usrIDText;
    private javax.swing.JButton usrTotalButton;
    private javax.swing.JButton verifButton;
    // End of variables declaration//GEN-END:variables
}
