/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MiniTwitter;

import java.awt.Color;
import java.util.Enumeration;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author yyan
 */
public class UserViewUI extends javax.swing.JFrame {
    
    private Group root;
    
    private User userInDialog = new User();
    
    public int msgSize;
    
    private DefaultListModel fList, mList;

    /**
     * Creates new form UserViewUI
     */
    public UserViewUI() {
        fList = new DefaultListModel();
        fList.addElement("following:");
        mList = new DefaultListModel();
        mList.addElement("messages: ");
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public UserViewUI(Group r, User u) {
        this.root = r;
        this.userInDialog.setID(u.getID());
        this.userInDialog.setFollowers(u.getFollowers());
        this.userInDialog.setFollowings(u.getFollowings());
        this.userInDialog.setMessage(u.getMessage());
        fList = new DefaultListModel();
        fList.addElement("following:");
        for(int i = 0; i < this.userInDialog.getFollowings().size(); i++) {
            fList.addElement("  " + this.userInDialog.getFollowings().get(i));
        }
        mList = new DefaultListModel();
        mList.addElement("Messages: ");
        for(int i = 0; i < this.userInDialog.getMessage().size(); i++) {
            fList.addElement("  " + this.userInDialog.getMessage().get(i));
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserViewPanel = new javax.swing.JPanel();
        usrIDText = new javax.swing.JTextArea();
        followButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        followingList = new javax.swing.JList<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgText = new javax.swing.JTextArea();
        postButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        msgList = new javax.swing.JList<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(userInDialog.getID());
        setMinimumSize(new java.awt.Dimension(400, 490));
        setName("ViewFrame"); // NOI18N
        setSize(new java.awt.Dimension(400, 490));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        UserViewPanel.setPreferredSize(new java.awt.Dimension(400, 490));

        usrIDText.setColumns(20);
        usrIDText.setForeground(new java.awt.Color(102, 102, 102));
        usrIDText.setRows(1);
        usrIDText.setText("Enter User ID");
        usrIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usrIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usrIDTextFocusLost(evt);
            }
        });

        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        followingList.setModel(fList);
        followingList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        followingList.setMaximumSize(new java.awt.Dimension(40, 85));
        followingList.setMinimumSize(new java.awt.Dimension(40, 85));
        followingList.setPreferredSize(new java.awt.Dimension(40, 85));
        jScrollPane2.setViewportView(followingList);

        msgText.setColumns(20);
        msgText.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        msgText.setForeground(new java.awt.Color(102, 102, 102));
        msgText.setLineWrap(true);
        msgText.setRows(4);
        msgText.setText("Tweet Message");
        msgText.setMinimumSize(new java.awt.Dimension(240, 20));
        msgText.setPreferredSize(new java.awt.Dimension(240, 80));
        msgText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                msgTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                msgTextFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(msgText);

        postButton.setText("Post");
        postButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postButtonActionPerformed(evt);
            }
        });

        msgList.setModel(mList);
        msgList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        msgList.setMaximumSize(new java.awt.Dimension(40, 85));
        msgList.setMinimumSize(new java.awt.Dimension(40, 85));
        msgList.setPreferredSize(new java.awt.Dimension(40, 85));
        jScrollPane5.setViewportView(msgList);

        javax.swing.GroupLayout UserViewPanelLayout = new javax.swing.GroupLayout(UserViewPanel);
        UserViewPanel.setLayout(UserViewPanelLayout);
        UserViewPanelLayout.setHorizontalGroup(
            UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserViewPanelLayout.createSequentialGroup()
                        .addComponent(usrIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(followButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(UserViewPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(postButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(UserViewPanelLayout.createSequentialGroup()
                        .addGroup(UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UserViewPanelLayout.setVerticalGroup(
            UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserViewPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usrIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(followButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(UserViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usrIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrIDTextFocusGained
        if(usrIDText.getText().equals("Enter User ID")) {
            usrIDText.setText("");
            usrIDText.setForeground(Color.black);
        }
    }//GEN-LAST:event_usrIDTextFocusGained

    private void usrIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usrIDTextFocusLost
        if(usrIDText.getText().equals("")) {
            usrIDText.setForeground(new Color(102, 102, 102));
            usrIDText.setText("Enter User ID");
        }
    }//GEN-LAST:event_usrIDTextFocusLost

    private void msgTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgTextFocusGained
        if(msgText.getText().equals("Tweet Message")) {
            msgText.setText("");
            msgText.setForeground(Color.black);
        }
    }//GEN-LAST:event_msgTextFocusGained

    private void msgTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msgTextFocusLost
        if(msgText.getText().equals("")) {
            msgText.setForeground(new Color(102, 102, 102));
            msgText.setText("Tweet Message");
        }
    }//GEN-LAST:event_msgTextFocusLost

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
        String text = usrIDText.getText();
        boolean alreadyIn = false;
        
        for(int i = 0; i < userInDialog.getFollowings().size(); i++) {
            if(userInDialog.getFollowings().get(i).equals(text)){
                alreadyIn = true;
                i = userInDialog.getFollowings().size();
            }
        }
        
        boolean userExist = false;
        DefaultMutableTreeNode ftemp = null;
        for(Enumeration e = root.depthFirstEnumeration(); e.hasMoreElements() && ftemp == null;) {
            DefaultMutableTreeNode uNode = (DefaultMutableTreeNode) e.nextElement();
            if(uNode.toString().equals(text) && (!uNode.getAllowsChildren())) {
                userExist = true;
                ftemp = uNode;
            }
        }
        
        if((!alreadyIn) && (userExist == true) && (!userInDialog.getID().equals(text))) {
            userInDialog.getFollowings().add(text);
            fList.addElement("  " + text);
            ftemp = null;
            User utemp = null;
            for(Enumeration e = root.depthFirstEnumeration(); e.hasMoreElements() && utemp == null;) {
                ftemp = (DefaultMutableTreeNode) e.nextElement();
                if(!ftemp.getAllowsChildren()) {
                    User uNode = (User) e.nextElement();
                    if(uNode.getID().equals(text)) {
                        uNode.getFollowers().add(text);
                    }
                }
            }
        }
    }//GEN-LAST:event_followButtonActionPerformed

    private void postButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postButtonActionPerformed
        String text = msgText.getText();
        msgSize++;
    }//GEN-LAST:event_postButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserViewUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserViewPanel;
    private javax.swing.JButton followButton;
    private javax.swing.JList<String> followingList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> msgList;
    private javax.swing.JTextArea msgText;
    private javax.swing.JButton postButton;
    private javax.swing.JTextArea usrIDText;
    // End of variables declaration//GEN-END:variables
}
